CREATE TABLE IF NOT EXISTS planet (
id VARCHAR(50) PRIMARY KEY CHECK (REGEXP_LIKE(id, '^[A-Z0-9]+$')),
name VARCHAR(500) NOT NULL CHECK (LENGTH(name) >= 2)
);

CREATE TABLE IF NOT EXISTS client(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(1000) NOT NULL CHECK (LENGTH(name) >= 2)
);

CREATE TABLE ticket (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
client_id BIGINT,
from_planet_id VARCHAR(50),
to_planet_id VARCHAR(50),
FOREIGN KEY (client_id) REFERENCES Client(id),
FOREIGN KEY (from_planet_id) REFERENCES Planet(id),
FOREIGN KEY (to_planet_id) REFERENCES Planet(id)
);
